=== RUN   TestZPanics
first output something
--- FAIL: TestZPanics (0.00s)
	main_test.go:35: then log something
	main_test.go:36: an error, why not
panic: boom [recovered]
	panic: boom

goroutine 6 [running]:
testing.tRunner.func1(0xc4200d41e0)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x51c5e0, 0x56c2b0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/util/failsuite/failsuitepanic.TestZPanics(0xc4200d41e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/failsuite/failsuitepanic/main_test.go:37 +0x113
testing.tRunner(0xc4200d41e0, 0x55c110)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200d41e0, 0x554258, 0xb, 0x55c110, 0x473276)
	/usr/local/go/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc4200d40f0)
	/usr/local/go/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc4200d40f0, 0xc420067dc8)
	/usr/local/go/src/testing/testing.go:777 +0xd0
testing.runTests(0xc42000c380, 0x609720, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc4200d6000, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x171
github.com/cockroachdb/cockroach/pkg/util/failsuite/failsuitepanic.TestMain(0xc4200d6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/failsuite/failsuitepanic/main_test.go:30 +0x52
main.main()
	_testmain.go:40 +0x151
FAIL	github.com/cockroachdb/cockroach/pkg/util/failsuite/failsuitepanic	0.006s

=== RUN   TestThatFails
--- FAIL: TestThatFails (0.00s)
	main_test.go:41: an error occurs
	main_test.go:42: then the test fatals

=== RUN   TestThatGetsSkipped
--- SKIP: TestThatGetsSkipped (0.00s)
	main_test.go:46: logging something
	main_test.go:47: skipped

=== RUN   TestParallelWithDataRaceAndFailures/6
=== PAUSE TestParallelWithDataRaceAndFailures/6
=== CONT  TestParallelWithDataRaceAndFailures/6
    --- FAIL: TestParallelWithDataRaceAndFailures/6 (0.01s)
    	main_test.go:81: subtest failed

=== RUN   TestParallelWithDataRaceAndFailures/9
=== PAUSE TestParallelWithDataRaceAndFailures/9
=== CONT  TestParallelWithDataRaceAndFailures/9
    --- FAIL: TestParallelWithDataRaceAndFailures/9 (0.46s)
    	main_test.go:81: subtest failed

=== RUN   TestParallelWithDataRaceAndFailures/0
=== PAUSE TestParallelWithDataRaceAndFailures/0
=== CONT  TestParallelWithDataRaceAndFailures/0
    --- FAIL: TestParallelWithDataRaceAndFailures/0 (0.75s)
    	main_test.go:81: subtest failed

=== RUN   TestParallelWithDataRaceAndFailures/3
=== PAUSE TestParallelWithDataRaceAndFailures/3
=== CONT  TestParallelWithDataRaceAndFailures/3
    --- FAIL: TestParallelWithDataRaceAndFailures/3 (0.46s)
    	main_test.go:81: subtest failed

=== RUN   TestParallelWithDataRaceAndFailures
output before calling t.Parallel()
=== PAUSE TestParallelWithDataRaceAndFailures
=== CONT  TestParallelWithDataRaceAndFailures
--- FAIL: TestParallelWithDataRaceAndFailures (0.00s)

